/**
 * Created by LDQ on 2017/5/9.
 */

export const GET_XB_LIST = 'GET_XB_LIST';
export const GET_PURCHASE_GAME_PRODUCT_LIST = 'GET_PURCHASE_GAME_PRODUCT_LIST';
export const CHANGE_PURCHASE_PRODUCT_LIST_SORT = 'CHANGE_PURCHASE_PRODUCT_LIST_SORT';
export const GET_PRODUCT_LIST_SHOP = 'GET_PRODUCT_LIST_SHOP';