/**
 * Created by LDQ on 2016/8/18.
 */

export const GET_SHOP_PRODUCT_INFO = 'GET_SHOP_PRODUCT_INFO';
export const INCREASE_SHOP_PRODUCT_NUM = 'INCREASE_SHOP_PRODUCT_NUM';
export const REDUCE_SHOP_PRODUCT_NUM = "REDUCE_SHOP_PRODUCT_NUM";
export const SET_SHOP_PRODUCT_BELONG = 'SET_SHOP_PRODUCT_BELONG';